# Generated by Django 5.1.2 on 2024-10-29 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ExchangeRate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                (
                    "quote",
                    models.CharField(
                        choices=[
                            ("EURUSD", "Euro to US Dollar"),
                            ("GBPUSD", "British Pound to US Dollar"),
                            ("INRUSD", "Indian Rupee to US Dollar"),
                            ("GBPINR", "British Pound to Indian Rupee"),
                            ("AEDINR", "UAE Dirham to Indian Rupee"),
                        ],
                        max_length=10,
                    ),
                ),
                ("open", models.FloatField()),
                ("high", models.FloatField()),
                ("low", models.FloatField()),
                ("close", models.FloatField()),
            ],
            options={
                "ordering": ["-date"],
                "unique_together": {("date", "quote")},
            },
        ),
    ]
